name: Build Supranova Executables

on:
  push:
    paths:
      - 'supranova'       # triggers only if the file changes
  workflow_dispatch:      # manual trigger

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install nuitka

      - name: Install MSVC Build Tools (Windows only)
        if: matrix.os == 'windows-latest'
        run: |
          choco install visualstudio2022buildtools --no-progress --yes --limit-output
          choco install visualstudio2022-workload-vctools --no-progress --yes --limit-output

      - name: Build Windows executable
        if: matrix.os == 'windows-latest'
        run: python -m nuitka Supranova.py --onefile --lto=yes --jobs=4 --windows-dependency-walker-auto-download=yes --output-filename=Supranova-windows-latest.exe

      - name: Build Linux executable
        if: matrix.os == 'ubuntu-latest'
        run: python -m nuitka supranova --onefile --lto=yes --jobs=4 --output-filename=Supranova-ubuntu-latest

      - name: Build macOS executable
        if: matrix.os == 'macos-latest'
        run: python -m nuitka supranova --onefile --lto=yes --jobs=4 --output-filename=Supranova-macos-latest

      - name: Upload Executable as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Supranova-${{ matrix.os }}
          path: |
            Supranova-windows-latest.exe
            Supranova-ubuntu-latest
            Supranova-macos-latest

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Linux Artifact
        uses: actions/download-artifact@v4
        with:
          name: Supranova-ubuntu-latest
          path: ./artifacts

      - name: Download Windows Artifact
        uses: actions/download-artifact@v4
        with:
          name: Supranova-windows-latest
          path: ./artifacts

      - name: Download macOS Artifact
        uses: actions/download-artifact@v4
        with:
          name: Supranova-macos-latest
          path: ./artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name || 'v1.0.0' }}
          name: Supranova Release ${{ github.ref_name || 'v1.0.0' }}
          files: ./artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
