name: Build Supranova Executable

on:
  push:
    paths:
      - "supranova"        # only trigger if this file changes
  workflow_dispatch:       # allow manual trigger

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"   # adjust if needed

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install -r requirements.txt
          python -m pip install nuitka

      - name: Build Executable with Nuitka
        run: |
          python -m nuitka supranova \
            --onefile --lto=yes --jobs=4 \
            --output-filename=Supranova_${{ matrix.os }}

      - name: Upload Executable Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Supranova-${{ matrix.os }}
          path: Supranova_${{ matrix.os }}*
